project:
  type: website
  resources: 
    - audio.mp3
    - Flag_of_Palestine_(vertical).svg
    - OPTIBuffer-Bold.otf
    - .well-known
    #- "_redirects"

website:
  title: "Yusuf Imaad Khan"
  site-url: https://www.yusufimaadkhan.com/blog
  description: "Rogue Analysis - Yusuf Imaad Khan's blog"
  navbar:
    background: primary
    left:
      # - href: index.qmd
      #   text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog - Rogue Analysis 📈 
      - href: resources.qmd
        text: Resources
      - href: watermelon.html
        text: 🍉
    right:
      - text: "Connect"
        menu:
          - icon: envelope
            text: Email
            href: mailto:yusuf.imaad.khan@gmail.com
          - icon: cloud
            text: Bluesky
            href: https://bsky.app/profile/yusufimaadkhan.com
          - icon: github
            text: Github
            href: https://github.com/yusufimaadkhan
            aria-label: GitHub
          - icon: person  
            text: PhilPeople
            href: https://philpeople.org/profiles/yusuf-imaad-khan
          - icon: graph-up-arrow
            text: Observable
            href: https://observablehq.com/@yusuf-imaad-khan
          - icon: book
            text: LSE Profile
            href: https://www.lse.ac.uk/government/people/research-students/yusuf-imaad-khan
          - icon: rss
            href: index.xml
  #reader-mode: true
  page-footer:
    left: "Built with [Quarto](https://quarto.org/), [GitHub](https://github.com/), [Netlify](https://netlify.com/), and [☕](/tea.qmd). [License: CC BY-SA 4.0.](https://creativecommons.org/licenses/by-sa/4.0/)"
    right:
      - icon: envelope
        href: mailto:yusuf.imaad.khan@gmail.com
      - icon: cloud
        href: https://bsky.app/profile/yusufimaadkhan.com
      - icon: github
        href: https://github.com/yusufimaadkhan
      - icon: person  
        href: https://philpeople.org/profiles/yusuf-imaad-khan
      - icon: graph-up-arrow
        href: https://observablehq.com/@yusuf-imaad-khan
      - icon: book
        href: https://www.lse.ac.uk/government/people/research-students/yusuf-imaad-khan
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: spacelab  #spacelab #flatly or lux
      #dark: cyborg #darkly
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    
editor: visual

