project:
  type: website

website:
  title: "Yusuf Imaad Khan"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: vapor
    css: styles.css
    toc: true

editor: visual

