project:
  type: website
  resources: 
    - "_redirects"

website:
  title: "Yusuf Imaad Khan"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Rogue Analysis
      #- about.qmd
    right:
      - icon: github
        href: https://github.com/yusufimaadkhan
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/yusuf_i_k 
        aria-label: Twitter
      - href: https://philpeople.org/profiles/yusuf-imaad-khan
        text: PhilPeople
  page-footer:
    right: "This website was built with [Quarto](https://quarto.org/), [GitHub](https://github.com/), and deployed with [Netlify](https://netlify.com/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."


format:
  html:
    theme:
      light: spacelab  #spacelab #flatly or lux
      dark: cyborg #darkly
    css: styles.css
    toc: true

editor: visual

