project:
  type: website
  resources: 
    - audio.mp3
    - Flag_of_Palestine_(vertical).svg
    - OPTIBuffer-Bold.otf
    - .well-known
    #- "_redirects"

website:
  title: "Yusuf Imaad Khan"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog - Rogue Analysis 📈 
      - href: resources.qmd
        text: Resources
      - href: watermelon.html
        text: 🍉
    right:
      - text: "Connect"
        menu:
          - icon: envelope
            text: Email
            href: mailto:yusuf.imaad.khan@gmail.com
          - icon: twitter
            text: Twitter
            href: https://twitter.com/yusuf_i_k 
            aria-label: Twitter
          - icon: mastodon
            text: Mastodon
            href: https://mastodon.online/@yusuf_i_k
          - icon: github
            text: Github
            href: https://github.com/yusufimaadkhan
            aria-label: GitHub
          - icon: person  
            text: PhilPeople
            href: https://philpeople.org/profiles/yusuf-imaad-khan
          - icon: book
            text: LSE Profile
            href: https://www.lse.ac.uk/government/people/research-students/yusuf-imaad-khan
  #reader-mode: true
  page-footer:
    right: "This website was built with [Quarto](https://quarto.org/), [GitHub](https://github.com/), [Netlify](https://netlify.com/), and [☕](tea.qmd). [License: CC BY-SA 4.0.](https://creativecommons.org/licenses/by-sa/4.0/)"


format:
  html:
    theme:
      light: spacelab  #spacelab #flatly or lux
      #dark: cyborg #darkly
    css: styles.css
    toc: true
    
editor: visual

